#!/usr/bin/python3
"""Defining..."""
from .rectangle import Rectangle


class Square(Rectangle):
    """Initilizing Square parameters."""

    def __init__(self, size, x=0, y=0, id=None):
        super().__init__(size, size, x, y)
        self.__size = size

    def __str__(self):
        return "[{}] ({}) {}/{} - {}".format(type(self).__name__,
                self.id, self.__x, self.__y, self.__width)
























